### ISSUE TITLE
filter_associations doesn't work when association class is different from association name

### ISSUE THREAD

**Issue by AmanShurafa** [oddcamp/active_hash_relation#30]
[This line in `ActiveHashRelation::AssociationFilters.filter_associations`](https://github.com/kollegorna/active_hash_relation/blob/master/lib/active_hash_relation/association_filters.rb#L16): ```association_name.singularize.constantize.unscoped.all```
assumes that the association name always matches the association class. As a result, the associations filter doesn't always work as expected on those rare instances where convention cannot be followed. 
Suggested change:
`association.class_name.constantize.unscoped.all`

**Comment by vasilakisfil** [comment]
ah interesting! Thanks for noticing out, will fix tonight!

**Comment by adammartak** [comment]
I found same problem with globalize gem, possible fix could be like here https://github.com/adammartak/active_hash_relation
